import imagenes from "../img/images";

export const productList = [
  {
    id: 1,
    title: "Caja temática Harry Potter",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.harrypotter,
    category: 1,
  },
  {
    id: 2,
    title: "Caja temática Lord of The Rings",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.lotr,
    category: 1,
  },
  {
    id: 3,
    title: "Caja temática Throne Of Glass",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.throneofglass,
    category: 1,
  },
  {
    id: 4,
    title: "Caja temática Percy Jackson",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.percyjackson,
    category: 1,
  },
  {
    id: 5,
    title: "Caja temática Maze Runner",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.mazerunner,
    category: 1,
  },
  {
    id: 6,
    title: "Caja temática Shadow Hunters",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.shadowhunters,
    category: 1,
  },
  {
    id: 7,
    title: "Caja temática Casey McQuiston",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.caseymcquiston,
    category: 1,
  },
  {
    id: 8,
    title: "Caja temática Stephen King",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.stephenking,
    category: 1,
  },
  {
    id: 9,
    title: "Caja temática Sherlock Holmes",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.sherlockholmes,
    category: 1,
  },
  {
    id: 10,
    title: "Caja temática Cuentos Clásicos",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.classicstories,
    category: 1,
  },
  {
    id: 11,
    title: "Caja temática Hermanas Bronte",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.brontesisters,
    category: 1,
  },
  {
    id: 12,
    title: "Caja temática Jane Austen",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.janeausten,
    category: 1,
  },
  {
    id: 13,
    title: "Caja temática Edgar Allan Poe",
    price: "5000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.eapoe,
    category: 1,
  },
  {
    id: 14,
    title: "Caja deluxe 31 days of reading",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.mesdelectura,
    category: 2,
  },
  {
    id: 15,
    title: "Caja deluxe Halloween",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.halloween,
    category: 2,
  },
  {
    id: 16,
    title: "Caja deluxe O.W.L.s",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.owls,
    category: 2,
  },
  {
    id: 17,
    title: "Caja deluxe N.E.W.T.s",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.newts,
    category: 2,
  },
  {
    id: 18,
    title: "Caja deluxe Fantasy Edition",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.fantasy,
    category: 2,
  },
  {
    id: 19,
    title: "Caja deluxe Romance Edition",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.romance,
    category: 2,
  },
  {
    id: 20,
    title: "Caja deluxe Horror Edition",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.horror,
    category: 2,
  },
  {
    id: 21,
    title: "Caja deluxe LGBTQ+ Edition",
    price: "9000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.lgbtq,
    category: 2,
  },
  {
    id: 22,
    title: "Suscripción mensual",
    price: "3500",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.mensual,
    category: 3,
  },
  {
    id: 23,
    title: "Suscripción bimensual",
    price: "6500",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.bimensual,
    category: 3,
  },
  {
    id: 24,
    title: "Suscripción trimestral",
    price: "9500",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.trimestral,
    category: 3,
  },
  {
    id: 25,
    title: "Suscripción semestral",
    price: "18500",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.semestral,
    category: 3,
  },
  {
    id: 26,
    title: "Suscripción anual",
    price: "38000",
    description: "Esta es la descripción del producto, trae varias cosas.",
    picture: imagenes.anual,
    category: 3,
  },
];

export const getList = (data, timeout) =>
  new Promise((res) =>
    setTimeout(() => {
      res(data);
    }, timeout)
  );
